# Generated by Django 4.2.30 on 2026-05-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0003_commande_commandeitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='reclamation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
    ]
