# Generated by Django 4.2.30 on 2026-05-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0004_reclamation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
